### ISSUE TITLE
Missing MK3 PSU cover 

### ISSUE THREAD

**Issue by libxmike** [prusa3d/Prusa-i3-Plus#60] opened 2018-02-27 07:32 UTC
I'm missing here SCAD/STL for PSU cover, can you add it?

**Comment by fiveangle** [comment] 2018-03-09 05:58
Dupe of #41 (and yes, it would be nice if they would post the file)

**Comment by stahlfabrik** [comment] 2018-04-19 20:08
Fixed now!

**Comment by Prusa-Support** [comment] 2022-05-10 08:16
The SCAD for the PSU cover has been added.

Marina Curzi
Prusa Research

**Closed as completed by Prusa-Support** 2022-05-10 08:16 UTC
