### ISSUE TITLE
PINDA holder sags in R4 revision

### ISSUE THREAD

**Issue by lff12** [prusa3d/Prusa-i3-Plus#136] opened 2019-07-16 23:42 UTC
After a lot of high temperature printing (Polymaker PC Max and generic HIPS), the PINDA holder begins to sag slightly, causing the sensor to tilt slightly to the left, and decreasing the accuracy of readings. Reseating the sensor and recalibrating the printer helps, but there is still a distinct sag. Parts for R4 self printed in Innofil PETG. Is it possible to reinforce the PINDA holder to prevent this?

**Comment by prusa3d-bb** [comment] 2019-07-18 11:06
Hello,
do you have any photos of this, which I could send to plastic parts developers? We are already reinforcing some parts, but I am not sure if this one is on the list too

Best Regards / S pozdravem
—
Jakub Kučera

Customer Support


_______________________________________

PRUSA Research

188/7a Partyzánská, 17000, Prague

+420 222 263 718

+421 220 570 305



Troubleshooting tutorials here!

Follow us on twitter and Facebook! 

Check out our blog!

________________________________________

Please rate our reply ...be generous :-)

--- original message ---
On July 17, 2019, 1:42 AM GMT+2 notifications@github.com wrote:


After a lot of high temperature printing (Polymaker PC Max and generic HIPS), the PINDA holder begins to sag slightly, causing the sensor to tilt slightly to the left, and decreasing the accuracy of readings. Reseating the sensor and recalibrating the printer helps, but there is still a distinct sag. Parts for R4 self printed in Innofil PETG. Is it possible to reinforce the PINDA holder to prevent this?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by lff12** [comment] 2019-07-19 00:26
![IMG_20190719_011128 (1)](https://user-images.githubusercontent.com/31033390/61500633-0a1f0500-a9c4-11e9-92d0-eaa2d1ba5c61.jpg)

**Comment by lff12** [comment] 2019-07-19 00:27
Sorry about the quality - i had a print in progress - but you can see that the PINDA is at an angle - its not caused by the position of the cable - it tilts to the right even if the cable is moved elsewhere.

**Comment by prusa3d-bb** [comment] 2019-07-19 15:39
Hello,
thank you for the photo. It is visible there. We are already reinforcing the parts around pinda probe. Do you need a replacement plastic part or can you print it yourself?

Best Regards / S pozdravem
—
Jakub Kučera

Customer Support


_______________________________________

PRUSA Research

188/7a Partyzánská, 17000, Prague

+420 222 263 718

+421 220 570 305



Troubleshooting tutorials here!

Follow us on twitter and Facebook! 

Check out our blog!

________________________________________

Please rate our reply ...be generous :-)

--- original message ---
On July 19, 2019, 2:27 AM GMT+2 notifications@github.com wrote:


Sorry about the quality - i had a print in progress - but you can see that the PINDA is at an angle - its not caused by the position of the cable - it tilts to the right even if the cable is moved elsewhere.

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by lff12** [comment] 2019-07-21 23:39
Very happy to print it myself, thanks! It also seems to be touching the cover and melting there - seems there is less gap between the heatsink and bottom of the cover than previous version! Thanks though.

**Comment by lff12** [comment] 2019-07-27 16:45
![IMG_20190727_130217](https://user-images.githubusercontent.com/31033390/61997198-1119d780-b096-11e9-9ba3-c77714bb5d81.jpg)
Here is a few photos of the old body after removal. Interestingly the fan part is perfect, it's just the body and cover that deformed. I'm replacing the parts today so will report back

**Comment by lff12** [comment] 2019-07-27 16:46
![IMG_20190727_140004](https://user-images.githubusercontent.com/31033390/61997214-6655e900-b096-11e9-98c4-4ec603aa64a3.jpg)

**Comment by prusa3d-bb** [comment] 2019-07-29 13:07
Hello,
thank you for the photos. The reinforced parts are done. You can print them. https://github.com/prusa3d/Original-Prusa-i3/tree/MK3S/Printed-Parts/STL​

Best Regards / S pozdravem
—
Jakub Kučera

Customer Support


_______________________________________

PRUSA Research

188/7a Partyzánská, 17000, Prague

+420 222 263 718

+421 220 570 305



Troubleshooting tutorials here!

Follow us on twitter and Facebook! 

Check out our blog!

________________________________________

Please rate our reply ...be generous :-)

--- original message ---
On July 27, 2019, 6:46 PM GMT+2 notifications@github.com wrote:



—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by maximlevitsky** [comment] 2019-07-29 21:53
Thank you!
Note that in my case the extruder cover melted right away after I preheated the printer to just PETG temperatures. 
PINDA seems to hold up, though.

**Comment by lff12** [comment] 2019-07-29 23:11
I've printed it, twice. First one had a small crack around the PINDA holder - but around the area where the screw and nut is so still holds ok - printed a second one. Have run a few prints with temps up to 270C - so far so good - will see in about 6 weeks if its still staying straight.

**Comment by prusa3d-bb** [comment] 2019-07-30 15:44
Hello,
if anything happens. please let us know, so we could reinforce it even more. Thank you

Best Regards / S pozdravem
—
Jakub Kučera

Customer Support


_______________________________________

PRUSA Research

188/7a Partyzánská, 17000, Prague

+420 222 263 718

+421 220 570 305



Troubleshooting tutorials here!

Follow us on twitter and Facebook! 

Check out our blog!

________________________________________

Please rate our reply ...be generous :-)

--- original message ---
On July 30, 2019, 1:11 AM GMT+2 notifications@github.com wrote:


I've printed it, twice. First one had a small crack around the PINDA holder - but around the area where the screw and nut is so still holds ok - printed a second one. Have run a few prints with temps up to 270C - so far so good - will see in about 6 weeks if its still staying straight.

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by prusa3d-bb** [comment] 2019-07-31 14:17
Hello,
could you please send me a photo of the new reinforced hotend cover, which was melted already? So it really melted after first heat up?

Best Regards / S pozdravem
—
Jakub Kučera

Customer Support


_______________________________________

PRUSA Research

188/7a Partyzánská, 17000, Prague

+420 222 263 718

+421 220 570 305



Troubleshooting tutorials here!

Follow us on twitter and Facebook! 

Check out our blog!

________________________________________

Please rate our reply ...be generous :-)

--- original message ---
On July 30, 2019, 5:44 PM GMT+2 info@prusa3d.com wrote:


Hello,

if anything happens. please let us know, so we could reinforce it even more. Thank you




Best Regards / S pozdravem

—

Jakub Kučera

Customer Support


_______________________________________

PRUSA Research

188/7a Partyzánská, 17000, Prague

+420 222 263 718

+421 220 570 305



Troubleshooting tutorials here!

Follow us on twitter and Facebook! 

Check out our blog!

________________________________________

Please rate our reply ...be generous :-)







> On July 30, 2019, 1:11 AM GMT+2 notifications@github.com wrote:


> I've printed it, twice. First one had a small crack around the PINDA holder - but around the area where the screw and nut is so still holds ok - printed a second one. Have run a few prints with temps up to 270C - so far so good - will see in about 6 weeks if its still staying straight.

> —

> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by maximlevitsky** [comment] 2019-07-31 14:24
@prusa3d-bb - no no, I haven't yet printed the reinforced hotend cover.
The old one, from the MK3S update melted right away.

I just wanted to note that in my case it melted without using higher that usual temperature, like needed for PC or so.

**Comment by maximlevitsky** [comment] 2019-07-31 14:26
I printed the update myself using the supplied PETG, and official gcode. Still I suspect that my printer might be a bit off in term of dimisions, so maybe the cover literaly touched the heater block, or even more likely its because I use the e3d sock which might cause the touching.

**Comment by maximlevitsky** [comment] 2019-07-31 14:28
Also it probably helped that ambients are here around 30C. (I basically have two choices: suffer from AC noise, or suffer from heat... )

**Comment by Moorviper** [comment] 2019-09-11 23:36
Why not use just ABS for the extruder part.
Many PETG are not better than PLA and deform when warmed up to 55-60°C for a longer period.

**Comment by prusa3d-bb** [comment] 2019-09-12 17:48
Hello,
PETG is printed much more easily. ABS warps too much. And we never had too many issues with the PETG. But you can use ABS or ASA to print the whole extruder

Best Regards / S pozdravem
—
Jakub Kučera

Customer Support


_______________________________________

PRUSA Research

188/7a Partyzánská, 17000, Prague

+420 222 263 718

+421 220 570 305



Troubleshooting tutorials here!

Follow us on twitter and Facebook! 

Check out our blog!

________________________________________

Please rate our reply ...be generous :-)

--- original message ---
On September 12, 2019, 1:36 AM GMT+2 notifications@github.com wrote:


Why not use just ABS for the extruder part.

Many PETG are not better than PLA and deform when warmed up to 55-60°C for a longer period.

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by francisdb** [comment] 2019-09-15 07:25
Same problem here since I built the [prusa lack enclosure](https://blog.prusaprinters.org/cheap-simple-3d-printer-enclosure/). I print a lot of PC / Nylon at high temperatures and the ambient temp in the enclosure reaches 35-40°C. The pinda probe started sagging and had to re-calibrate 1st layer twice already.

For reference:
https://forum.prusaprinters.org/forum/original-prusa-i3-mk3s-mk3-hardware-firmware-and-software-help/mk3s-part-melted/

Has the pinda probe part also been reinforced in R5 or only the cover? Any suggestions for a better material than PETG for this part?

**Comment by prusa3d-bb** [comment] 2019-09-18 22:09
Hello,
pinda probe holder has been also reinforced as you can see here https://github.com/prusa3d/Original-Prusa-i3/tree/MK3S/Printed-Parts/STL
I recommend using PETG or ABS/ASA. We just released Prusament ASA, which you can use. 

Best Regards / S pozdravem
—
Jakub Kučera

Customer Support


_______________________________________

PRUSA Research

188/7a Partyzánská, 17000, Prague

+420 222 263 718

+421 220 570 305



Troubleshooting tutorials here!

Follow us on twitter and Facebook! 

Check out our blog!

________________________________________

Please rate our reply ...be generous :-)

--- original message ---
On September 15, 2019, 9:25 AM GMT+2 notifications@github.com wrote:


Same problem here since I built the prusa lack enclosure. I print a lot of PC / Nylon at high temperatures and the ambient temp in the enclosure reaches 35-40°C. The pinda probe started sagging and had to re-calibrate 1st layer twice already.

For reference:

https://forum.prusaprinters.org/forum/original-prusa-i3-mk3s-mk3-hardware-firmware-and-software-help/mk3s-part-melted/

Has the pinda probe part also been reinforced or only the cover? Any suggestions for a better material than PETG for this part?

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by embusalacchi** [comment] 2019-10-07 20:45
Hi!  Just wanted to report that my original hot end cover has started to sag with only PETG printing.  I was printing the replacement in PETG so I'm glad that's when it started to sag.  I'm not seeing it with the PINDA holder though.  I plan on replacing the cover in the next few days assuming I get the time.  I can report back if it sags again.

**Comment by Rubines** [comment] 2020-02-03 13:47
Hi

I also had the sagging pinda problem and ignored it, until the probe holder broke,..
The problematic section is where the square nut is positionend, there is verry little supporting structure around it. Unfortunately I cannot find the improved version anymore, the R4 Version started to sag pretty quickly.
![IMG_1763](https://user-images.githubusercontent.com/4949912/73658070-eab3a500-4693-11ea-9cdb-beaf73f8daa7.jpg)

**Comment by prusa3d-bb** [comment] 2020-02-04 14:20
Hello,
please contact Prusa support directly on the email info@prusa3d.com or on the online chat, which is located on the eshop bottom right corner to sort out the replacement of this part. Thank you

**Comment by wjsteele** [comment] 2020-04-07 01:42
Just as an FYI... I just experienced this same failure during an extended print at 250C (Prusament PETG) where the Pinda probe sagged and came in contact with the print.  I was able to pause the print and move it up, but will need to repair it before the next print.

I might add, my machine is only a few weeks old... so it has the updated design, I presume.

**Comment by rafepurnell** [comment] 2020-04-26 10:41
I have had the same issue and have melted 3 of these reinforced PINDA holders. I'm starting to worry about finding a solution. 

Right now my CR10 is my savoir. 

Is the right path to get the BondTech upgrade or is there another solution for this problem.

I loved my MK3 before the MK3S upgrade. :(

**Comment by observatoer** [comment] 2020-04-26 10:45
Based on what I have tried, the Bondtech upgrade extruder and the Bear extruder have both no issue with the pinda holder. You shall to run them with a Sunon fan to cool the hotted properly.

**Comment by Rubines** [comment] 2020-04-28 12:17
Hi

The new design update solved all my troubles even when printing @250 °C for 18 hours.
At first I was sceptic but after a while all my concerns were gone.

**Comment by Prusa-Support** [comment] 2022-05-10 11:51
Hello! Sorry for the late response to this thread. Closing the thread as the reinforcing aspect is solved - of course, in case of any further specific issues related with this, do not hesitate to let us know by contacting our Technical Support info@prusa3d.com at any time, we'll help with anything and check each case one by one. 

Alessandro Pantaleo
Prusa Research

**Closed as completed by Prusa-Support** 2022-05-10 11:51 UTC
